name: Build and Deploy Docker Image

on:
  push:
    branches:
      - master  # Change this to 'master' since that's your branch name
    paths:
      - '**/*'  # Trigger when any file changes in the repository

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Docker Buildx (Optional, but can help with advanced features)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # Step 3: Log in to Azure Container Registry (ACR)
    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: chatbotllmtest.azurecr.io  # Replace <YOUR_ACR_NAME> with your ACR name
        username: chatbotllmtest  # GitHub Secret for ACR username
        password: HlTM7Y6nxQlWKJuAGkjSkxed/vZ00evP/IqsY2nEsj+ACRCLp2gK  # GitHub Secret for ACR password

    # Step 4: Build Docker Image
    - name: Build Docker image
      run: |
        docker build -t chatbotllmtest.azurecr.io/chatbottest:1 .

    # Step 5: Push Docker Image to ACR
    - name: Push Docker image to ACR
      run: |
        docker push chatbotllmtest.azurecr.io/chatbottest:1   # Replace <YOUR_ACR_NAME> and <image_name>

    # Step 6: Deploy to Azure Container App
    - name: Deploy to Azure Container App
      uses: azure/azure-container-apps-deploy@v1
      with:
        azure_subscription: fe900839-6d9b-4e8e-9ca9-021babff604a  # GitHub Secret for Azure Subscription ID
        resource_group: chatbot_test  # Replace <resource_group_name> with your Azure resource group name
        container_app_name: llm-server-test  # Replace <container_app_name> with your Azure Container App name
        image_name: chatbotllmtest.azurecr.io/chatbottest:1  # Image pushed to ACR
