name: Build and Deploy Docker Image

on:
  push:
    branches:
      - master  # Change this if your branch name is different
    paths:
      - '**/*'  # Trigger on any file change

jobs:
  build_and_push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ACR_NAME }}.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Get Latest Image Tag
        id: get_tag
        run: |
          TAG=$(az acr repository show-tags --name ${{ secrets.ACR_NAME }} --repository chatbottest --orderby time_desc --output tsv | head -n 1)
          if [[ -z "$TAG" ]]; then
            NEW_TAG=v1
          else
            NEW_VERSION=$(( ${TAG#v} + 1 ))
            NEW_TAG="v$NEW_VERSION"
          fi
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV
          echo "New Docker Image Tag: $NEW_TAG"

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/chatbottest:${{ env.NEW_TAG }} .
          docker tag ${{ secrets.ACR_NAME }}.azurecr.io/chatbottest:${{ env.NEW_TAG }} ${{ secrets.ACR_NAME }}.azurecr.io/chatbottest:latest

      - name: Push Docker Image to ACR
        run: |
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/chatbottest:${{ env.NEW_TAG }}
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/chatbottest:latest

  # deploy:
  #   name: Deploy to Azure Container App
  #   needs: build_and_push
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Log in to Azure
  #       uses: azure/login@v1
  #       with:
  #         creds: ${{ secrets.AZURE_CREDENTIALS }}

  #     - name: Deploy to Azure Container App
  #       run: |
  #         az containerapp update \
  #           --name ${{ secrets.AZURE_CONTAINER_APP_NAME }} \
  #           --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
  #           --image ${{ secrets.ACR_NAME }}.azurecr.io/chatbottest:${{ env.NEW_TAG }} \
  #           --revision-suffix rev-${{ env.NEW_TAG }}
